### ISSUE TITLE
Research: Plugins in browsers

### ISSUE THREAD

**Issue by savin000** [VSU-CS-MCS/recommendations-system-ui#1]
Find more info about developing plugins for the Web Application that is used in browser. How can we send requests and update page info. How to embed our own scripts / html / styles. Do we need additional JS service to make it work with our backend?

**Comment by Mr-Keltt** [comment]
[Браузерное расширение.docx](https://github.com/VSU-CS-MCS/recommendations-system-ui/files/10834319/default.docx)
