### ISSUE TITLE
find specific technology stack that can perform HTTP-requests

### ISSUE THREAD

**Issue by savin000** [VSU-CS-MCS/recommendations-system-ui#5]
I assume that React is the best solution, because it is minimalistic and have everything that we need, but please do some research, maybe there are some modern more lightweight frameworks that can do our tasks (build form with inputs/buttons/maybe redirect/graphs and do HTTP calls). Or its better to go with plain js/html/css with some libraries

**Comment by Mr-Keltt** [comment]
[Стек технологий для фронта.docx](https://github.com/VSU-CS-MCS/recommendations-system-ui/files/10874439/default.docx)
